-- ============================================================
-- LEGACY: catálogo de platos
-- ============================================================
-- IMPORTANTE: este archivo ya no debe ejecutarse como instalación.
-- La versión actual y segura está en:
-- supabase/migrations/20260913120000_hardening_menu.sql
--
-- Esta migración histórica contenía un TRUNCATE de pedidos, días y
-- semanas. Se elimina deliberadamente para evitar pérdida accidental
-- de datos.
--
-- El esquema canónico actualizado se encuentra en schema.sql.
-- Para una base existente, aplicar las migraciones de Supabase.
