-- ============================================================
-- LEGACY: crear_semana
-- ============================================================
-- La implementación vigente se encuentra en:
-- supabase/migrations/20260913120000_hardening_menu.sql
--
-- Este archivo se conserva solo como referencia histórica para no
-- mantener dos versiones diferentes de la función.
-- No ejecutar esta versión sobre una base actual.
