-- =========================================================
-- Todo Artesanal v2 — Fase 4
-- 04_admin_setup.sql
--
-- Responsabilidad:
--   - insertar el primer usuario administrador.
--
-- NO incluye:
--   - creación de admin_users;
--   - funciones de seguridad;
--   - RLS;
--   - policies;
--   - lógica de negocio.
--
-- Todo lo anterior pertenece a 03_rls.sql.
--
-- IMPORTANTE:
--   El INSERT del primer admin está comentado a propósito.
--   Motivo: no puede contener un UUID placeholder porque la
--   columna user_id es de tipo uuid y el cast fallaría al
--   aplicar la migración.
--
--   Pasos para configurar el primer admin:
--
--   1. Crear el usuario en Supabase Auth:
--        Dashboard → Authentication → Users → Add user
--
--   2. Copiar el UUID del usuario creado.
--
--   3. Ejecutar el INSERT de la sección siguiente,
--      reemplazando el UUID de ejemplo.
--
--   4. (Opcional) Confirmar:
--        select * from private.admin_users;
-- =========================================================


-- =========================================================
-- PRIMER ADMINISTRADOR
-- =========================================================
--
-- Reemplazar el UUID de ejemplo por el UUID real del usuario
-- creado en auth.users y descomentar el bloque.
--
-- El UUID puede obtenerse desde:
--   - Supabase Dashboard → Authentication → Users
--   - O con esta query:
--       select id, email
--       from auth.users
--       order by created_at;
-- =========================================================

-- insert into private.admin_users (user_id)
-- values ('00000000-0000-0000-0000-000000000000')
-- on conflict (user_id) do nothing;


-- =========================================================
-- AGREGAR FUTUROS ADMINISTRADORES
-- =========================================================
--
-- Los administradores adicionales se agregan manualmente
-- insertando el UUID correspondiente de auth.users:
--
--   insert into private.admin_users (user_id)
--   values ('UUID-DEL-NUEVO-ADMIN')
--   on conflict (user_id) do nothing;
--
-- Para quitar un administrador:
--
--   delete from private.admin_users
--   where user_id = 'UUID-DEL-ADMIN';
--
-- No modificar auth.users desde este archivo.
--
-- Nota: la tabla private.admin_users tiene FK a auth.users(id)
-- con ON DELETE CASCADE. Si un usuario de auth es eliminado,
-- su fila correspondiente en admin_users también se elimina
-- automáticamente.
-- =========================================================